spring.application.name=travelappserver
spring.datasource.username=ayungi
spring.datasource.password=ekz0Obitch13$

spring.datasource.url=jdbc:postgresql://194.87.110.27:5432/travel_app_db

spring.jpa.hibernate.ddl-auto=update
server.address=0.0.0.0
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.datasource.hikari.auto-commit=false

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=byekzonek@gmail.com
spring.mail.password=szxauzixrtimzdhj
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.verification.token.expiration.minutes=60
app.password.reset.token.expiration.minutes=30
